on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: ezinvoice CI on ECR

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Create env file
      env:
        QA_ENV_FILE: ${{ EZINVOICE_ENV_FILE }}
      run: |
        echo $QA_ENV_FILE | base64 --decode > .env
               
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}      
          
    - name: Build, tag, and push image to Docker
      id: build-image
      run: |
        # Build a docker container and push it to docker 
        docker build -t phillux1978/envtest:latest .
        docker push phillux1978/envtest:latest
        
